/**
 * Constants used in the UI.
 */
export class PillarsConstants {
 // Base width and height. Position everything as if it's this
    // size and then scale it to the actual size.
    static readonly BW = 1920;
    static readonly BH = 1200;
    static readonly PROPORTION = PillarsConstants.BW / PillarsConstants.BH;
    static readonly MARKETX = 5;
    static readonly MARKETY = 270;
    static readonly MARKETW = PillarsConstants.BW - 250;
    static readonly HOVER_START = 'hover_';
    static readonly INPLAY_START_KEY = 'inplay_start';
    static readonly INPLAY_HOVER_KEY = PillarsConstants.HOVER_START + 'inplay';
    static readonly INPLAY_AREA_KEY = PillarsConstants.INPLAY_START_KEY + '_area'
    static readonly MARKET_START_KEY = 'market_';
    static readonly MARKET_HOVER_KEY = PillarsConstants.HOVER_START + 'market_';
    static readonly HAND_START_KEY = 'hand_';
    static readonly HAND_HOVER_KEY = PillarsConstants.HOVER_START + 'hand_';
    static readonly DISCARD_START_KEY = 'discard_';
    static readonly DISCARD_HOVER_KEY = PillarsConstants.HOVER_START + 'discard_';
    static readonly DISCARD_AREA_KEY = 'disc_area'; // Don't start with discard_
    static readonly DECKH = 300;
    static readonly DECKX = 25;
    static readonly DECKY = PillarsConstants.BH - PillarsConstants.DECKH;
    static readonly HAND_X = 250;
    static readonly HAND_Y = PillarsConstants.BH - PillarsConstants.DECKH;
    static readonly HAND_WIDTH = 700;
    static readonly DISCARD_X = PillarsConstants.HAND_X + PillarsConstants.HAND_WIDTH + 50;
    static readonly DISCARD_Y = PillarsConstants.BH - PillarsConstants.DECKH;
    static readonly FELT_RADIUS = 20;
    static readonly CARD_WIDTH = 200; 
    static readonly CARD_HEIGHT = 275;
    static readonly CARD_RADIUS = 15;
    static readonly CARD_IMAGE_SCALE = 0.285;
    static readonly INPLAYX = 5;
    static readonly INPLAYY = PillarsConstants.MARKETY + PillarsConstants.CARD_HEIGHT + 25;
    static readonly INPLAYW = PillarsConstants.MARKETW + 20;
    static readonly INPLAYH = PillarsConstants.CARD_HEIGHT + 20;
    static readonly BIGCARDX = PillarsConstants.INPLAYX + PillarsConstants.INPLAYW + 15;
    static readonly BIGCARDY = PillarsConstants.MARKETY;
    static readonly PILLAR_SCALE = 0.8;
    static readonly PILLARX = PillarsConstants.BW - 180;
    static readonly PILLARY = 70;
    static readonly PILLAR_START_KEY = 'pillar_';
    static readonly COLOR_WHITE = 'white';
    static readonly COLOR_BLACKISH = '#212121';
    static readonly COLOR_WHITEISH = '#FAFAFA';
    static readonly MODALX = 200;
    static readonly MODALY = 200;
    static readonly MODALW = PillarsConstants.BW - 400;
    static readonly MODALH = PillarsConstants.BH - 400;
    static readonly MODALR = 50;
    static readonly MODALZ = 900;
    static readonly MODAL_KEY = 'modal';
    static readonly MODAL_CLOSE_KEY = 'modal_close';
    static readonly MODAL_HREF_KEY = 'modal_href';
    static readonly MODAL_CARD_ACTION_SCALE = 1.5;
    static readonly TRIALX = PillarsConstants.BW/2 - PillarsConstants.CARD_WIDTH/2;
    static readonly TRIALY = PillarsConstants.MODALY + 200;
    static readonly TRIAL_START_KEY = 'trial_';
    static readonly TRIAL_HOVER_KEY = PillarsConstants.HOVER_START + 'trial';
    static readonly TRIAL_OFFSET = 23;
    static readonly INFO_KEY = 'info';
    static readonly POPUP_SCALE = 2.28;
    static readonly DICEX = 1600;
    static readonly DICEY = 120;
    static readonly CHATX = 750;
    static readonly CHATY = 10;
    static readonly CHATW = 900;
    static readonly CHATH = 250;
    static readonly COMPETITIVE_RESEARCH_KEY = PillarsConstants.MODAL_KEY + '_cr';
    static readonly NUMERALS = ['I', 'II', 'III', 'IV', 'V'];
    static readonly SUMMARYX = 10;
    static readonly SUMMARYY = PillarsConstants.CHATY;
    static readonly SUMMARYW = 350;
    static readonly SUMMARYH = 125;
    static readonly MENUX = PillarsConstants.MODALX + 500;
    static readonly MENUY = PillarsConstants.MODALY + 200;
    static readonly MENUW = 200;
    static readonly MENUH = 120;
    static readonly MENU_BUTTON_W = 125;
    static readonly MENU_BUTTON_H = 30;
    static readonly REGION_MARKET = 'region_market';
    static readonly REGION_HAND = 'region_hand';
    static readonly REGION_DISCARD = 'region_discard';
    static readonly REGION_INPLAY = 'region_inplay';
}